### ISSUE TITLE
Database error during insertion of Literature / SRU Search 

### ISSUE THREAD

**Issue by banditjt** [streldev/moodle-mod_literature#5]
Hi there,

if we try to insert literature data into a course, we sometimes get the following error:

**Error Log:**
Error code: dmlwriteexception
* line 446 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 244 of /lib/dml/pgsql_native_moodle_database.php: call to
moodle_database->query_end()
* line 868 of /lib/dml/pgsql_nati" while reading response header from
upstream, client: 147.172.2.11, server: www.uni-hildesheim.de, request:
"POST
/lwdemo/mod/literature/lit/search.php?course=1569&section=0%20%20%20%20%20%20%20%20%20%20%20%20&search=redo
HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host:
"www.uni-hildesheim.de", referrer:"https://www.uni-hildesheim.de/lwdemo/mod/literature/lit/search.php?course=1569&section=0&source=1&text=darwin&search=quick"
2016/04/22 09:09:14 [error] 4725#0: *8420 FastCGI sent in stderr: "PHP
message: PHP Notice:  Trying to get property of non-object in
/data/learnweb2015/htdocs/lwdemo/mod/literature/locallib.php on line 889
PHP message: PHP Warning:  Creating default object from empty value in
/data/learnweb2015/htdocs/lwdemo/mod/literature/locallib.php on line 890
PHP message: Default exception handler: Fehler beim Schreiben der
Datenbank Debug: ERROR:  null value in column "type" violates not-null
constraint
DETAIL:  Failing row contains (38, null, , , null, null, null, null, , ,
null, null, null, null, null, 0).
INSERT INTO mdl_literature_lit
(type,title,subtitle,authors,publisher,published,series,isbn10,isbn13,issn,coverpath,description,format,titlelink,refs)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id
[array (
  'type' => NULL,
  'title' => '',
  'subtitle' => '',
  'authors' => NULL,
  'publisher' => NULL,
  'published' => NULL,
  'series' => NULL,
  'isbn10' => '',
  'isbn13' => '',
  'issn' => NULL,
  'coverpath' => NULL,
  'description' => NULL,
  'format' => NULL,
  'titlelink' => NULL,
  'refs' => 0,
)]

If this error occurs the first time we have to log off and on, to be able to add literature with this Plugin again. 
Our Moodle Data:

**Moodle-Data**:
Moodle 2.9.4+ (Build: 20160129)
Postgress 9.3 Database is used
PHP Version 5.5.9**

You got any ideas? Should we provide any more information? Please ask us!

Greetings

**Comment by streldev** [comment]
Hi Timo,

first of all i have to apologize fpr answering this late. I developed this plugin a few years ago for my bachelor thesis and nearly forgott about it. I will invest some time on the weekend and check if i can find something related to your message.

Greetings, Freddy

**Comment by banditjt** [comment]
Hi Freddy,

no apologizes needed :) . Your Plugin is really great for using it in University context. If we can provide you with any information - please ask. We are also able to provide you access to our demo environment if needed. 

Greetings, Timo

**Comment by streldev** [comment]
Hi Timo,

found the bug and fixed it. Just pull the fix and give it a try. 

Greetings, Freddy

**Comment by banditjt** [comment]
Hi Freddy,

ur Fix is just working fine - tank you for your Support!!!!

Greetings 

Timo
